version: '3.8'

services:
  # PostgreSQL Database - 优化版
  postgres:
    image: postgres:15-alpine
    container_name: matrix-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-synapse}
      - POSTGRES_USER=${POSTGRES_USER:-synapse}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - matrix-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
        reservations:
          memory: 256M
          cpus: '0.1'

  # Synapse Matrix Server - 极简优化版
  synapse:
    build: 
      context: .
      dockerfile: Dockerfile.minimal
    container_name: matrix-synapse
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      # Server configuration
      - SYNAPSE_SERVER_NAME=${MATRIX_SERVER_NAME}
      - SYNAPSE_REPORT_STATS=${REPORT_STATS:-no}
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      
      # Database configuration
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-synapse}
      - POSTGRES_USER=${POSTGRES_USER:-synapse}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      
      # Security secrets
      - REGISTRATION_SHARED_SECRET=${REGISTRATION_SHARED_SECRET}
      - MACAROON_SECRET_KEY=${MACAROON_SECRET_KEY}
      - FORM_SECRET=${FORM_SECRET}
      
      # Feature flags
      - ENABLE_REGISTRATION=${ENABLE_REGISTRATION:-false}
      - FRIENDS_ENABLED=${FRIENDS_ENABLED:-true}
      
      # 极简性能优化
      - SYNAPSE_CACHE_FACTOR=0.2
      - SYNAPSE_EVENT_CACHE_SIZE=500
      - SYNAPSE_WORKERS=none
    volumes:
      - synapse_data:/data
      - synapse_media:/media
    networks:
      - matrix-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.7'
        reservations:
          memory: 512M
          cpus: '0.3'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  # Well-known server discovery - 轻量版
  well-known:
    image: nginx:alpine
    container_name: matrix-well-known
    restart: unless-stopped
    volumes:
      - ./well-known:/usr/share/nginx/html:ro
    networks:
      - matrix-network
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.05'

# Volume definitions
volumes:
  postgres_data:
    driver: local
  synapse_data:
    driver: local
  synapse_media:
    driver: local

# Network definition
networks:
  matrix-network:
    driver: bridge