# 极简版 homeserver.yaml
# 专为单核CPU 2G内存服务器优化

server_name: "${MATRIX_SERVER_NAME}"
pid_file: /data/homeserver.pid
web_client: false
public_baseurl: "https://${MATRIX_SERVER_NAME}/"

# 监听配置 - 极简版
listeners:
  - port: 8008
    tls: false
    bind_addresses: ['0.0.0.0']
    type: http
    x_forwarded: true
    
    resources:
      - names: [client, federation]
        compress: false  # 减少CPU使用

# 数据库配置 - 优化连接池
database:
  name: psycopg2
  args:
    user: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    database: "${POSTGRES_DB}"
    host: postgres
    port: 5432
    cp_min: 1          # 最小连接数
    cp_max: 2          # 最大连接数
    connect_timeout: 10
    keepalives: 1
    keepalives_idle: 10
    keepalives_interval: 10
    keepalives_count: 3

# 日志配置 - 简化日志
log_config: "/data/synapse.log.config"
log_level: "WARNING"
log_root: "/data"

# 媒体存储配置
media_store_path: "/data/media"
uploads_path: "/data/uploads"

# 性能优化 - 关键配置
caches:
  global_factor: 0.2        # 缓存因子降至0.2
  event_cache_size: 500      # 事件缓存降至500
  
# 数据库性能优化
database_config:
  allow_unsafe_locale: true
  txn_limit: 100
  search_all_users: false

# 事件流配置
event_cache_size: 500
event_window_size: 100

# 注册配置
enable_registration: ${ENABLE_REGISTRATION}
registration_shared_secret: "${REGISTRATION_SHARED_SECRET}"

# 好友功能配置
friends:
  enabled: ${FRIENDS_ENABLED}
  max_friends_per_user: 50   # 减少好友数量限制
  rate_limiting:
    max_requests_per_hour: 5
    rate_limit_window: 3600

# 速率限制 - 严格限制
rc_registration:
  per_second: 0.1     # 每10秒一个请求
  burst_count: 3

rc_login:
  per_second: 0.2     # 每5秒一个请求
  burst_count: 3

rc_message:
  per_second: 0.5     # 每2秒一个消息
  burst_count: 10

rc_admin_redaction:
  per_second: 0.1
  burst_count: 3

# 联邦配置 - 限制资源使用
federation_client_config:
  min_cached_server_keys: 10
  max_cached_server_keys: 50
  server_name_cache_size: 50

# 媒体配置
max_upload_size: "5M"          # 限制上传大小
media_retention:
  remote_media_lifetime: "3d"   # 远程媒体保留3天
  local_media_lifetime: "7d"    # 本地媒体保留7天

# 动态模块 - 禁用不必要的模块
modules:
  - module: "synapse.module.federation.FederationSender"
    config:
      instance_name: "minimal"
    enabled: false

# 服务器通知 - 禁用以节省资源
server_notices:
  enabled: false

# 统计配置
report_stats: ${REPORT_STATS}

# 隐私设置
allow_public_rooms_over_federation: false
allow_public_rooms_without_auth: false

# 安全配置
macaroon_secret_key: "${MACAROON_SECRET_KEY}"
form_secret: "${FORM_SECRET}"

# Redis配置 - 如果启用的话
redis:
  enabled: false   # 极简版禁用Redis

# 工作进程 - 单进程模式
worker_main: null

# 客户端配置
client_config:
  dynamic_thumbnails: false
  url_preview_enabled: false

# 推送配置 - 禁用以节省资源
push:
  enabled: false

# 电子邮件配置 - 禁用
email:
  enabled: false

# 验证码配置 - 禁用
registration_requires_verification: false